# Generated by Django 2.2.6 on 2019-10-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191023_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='图片名称'),
        ),
    ]
